---
- hosts: localhost
  connection: local
  tasks:
    - name: Install macvim
      shell: brew install macvim --override-system-vim
      args:
        creates: /usr/local/bin/mvim

    - name: Get Homebrew/Versions
      shell: brew tap homebrew/versions
      args:
        creates: /usr/local/Library/Taps/homebrew/homebrew-versions

    - name: Uninstall Homebrew packages
      homebrew: name={{ item }} state=absent
      with_items:
        - phantomjs # avoiding 2.0: https://github.com/ariya/phantomjs/issues/12506

    - name: Install Homebrew packages
      homebrew: name={{ item }} state=present update_homebrew=yes
      with_items:
        - ack
        - awscli
        - ctags
        - hg
        - hub
        - imagemagick
        - jq
        - phantomjs198
        - rbenv
        - ruby-build
        - terraform
        - tmux
        - unrar
        - wget

    - name: Install Casks
      homebrew_cask: name={{ item }} state=present
      with_items:
        - atom
        - cord
        - dropbox
        - firefox
        - google-chrome
        - harvest
        - heroku-toolbelt
        - intellij-idea-ce
        - iterm2
        - lastpass
        - postgres
        - screenhero
        - skitch
        - skype
        - slack
        - postgres
        - virtualbox

    - name: Install janus
      shell: curl -Lo- https://bit.ly/janus-bootstrap | bash
      args:
        creates: ~/.vim/janus

    - name: Create vim plugin directory
      file: state=directory path=~/.janus

    - name: Install vim plugins
      git: repo={{ item.repo }} dest={{ item.dest }}
      with_items:
        - { repo: 'https://github.com/skalnik/vim-vroom.git', dest: '~/.janus/vim-vroom' }
        - { repo: 'https://github.com/benmills/vimux.git', dest: '~/.janus/vimux' }
        - { repo: 'https://github.com/tpope/vim-cucumber.git', dest: '~/.janus/vim-cucumber' }
        - { repo: 'https://github.com/airblade/vim-gitgutter.git', dest: '~/.janus/vim-gitgutter' }
        - { repo: 'https://github.com/vim-scripts/ruby-matchit.git', dest: '~/.janus/ruby-matchit' }
        - { repo: 'https://github.com/kana/vim-textobj-user.git', dest: '~/.janus/vim-textobj-user' }
        - { repo: 'https://github.com/nelstrom/vim-textobj-rubyblock.git', dest: '~/.janus/vim-textobj-rubyblock' }
        - { repo: 'https://github.com/michaeljsmith/vim-indent-object.git', dest: '~/.janus/vim-indent-object' }

    - name: Ensure ~/code exists
      file: path={{ "~/code" | expanduser }} state=directory

    - name: Install python packages
      become: yes
      pip: name=boto state=present
